(()=>{
'use strict';
const STORAGE='bardo-kanban-qa-v4';
const VERSION=4;
const ME='ma';
const MAX_COLUMNS=8,MAX_LABELS=8,MAX_SUBTASKS=40,MAX_COMMENTS=100;
const people=[
{id:'ma',name:'Maxi',initials:'MA'},{id:'al',name:'Alejandra',initials:'AL'},{id:'ca',name:'Camila',initials:'CA'},
{id:'da',name:'Daniela',initials:'DA'},{id:'fe',name:'Felipe',initials:'FE'},{id:'jo',name:'José',initials:'JO'},
{id:'lu',name:'Lucas',initials:'LU'},{id:'so',name:'Sofía',initials:'SO'}
];
const priorities=['low','normal','high','urgent'];
const priorityLabel={low:'Baja',normal:'Normal',high:'Alta',urgent:'Urgente'};
const priorityRank={urgent:0,high:1,normal:2,low:3};
const labelsPool=['UX','UI','Bug','Research','Content','Backend','Frontend','QA','A11y','Discord','Cloudflare','Mobile','Design System','Docs','Analytics'];
const sources=['Manual','Discord','Docs','Planner','Reunión'];
const titleStarts=['Revisar','Diseñar','Validar','Implementar','Corregir','Documentar','Probar','Refinar','Preparar','Investigar','Optimizar','Alinear'];
const titleEnds=['flujo de creación rápida','estados vacíos','navegación móvil','drag & drop','filtros del tablero','jerarquía visual','accesibilidad del detalle','persistencia local','integración con Docs','mensajes de error','microcopy de acciones','rendimiento con volumen','responsive en iPhone','selector de responsables','atajos de teclado','recuperación tras borrado','columnas personalizadas','búsqueda global','fechas límite','subtareas y comentarios'];
const descriptions=[
'Validar el comportamiento completo con datos mock y registrar cualquier fricción antes de integrar el módulo definitivo.',
'Caso de prueba pensado para revisar densidad, legibilidad, estados extremos y comportamiento en pantallas pequeñas.',
'Revisar con foco en carga cognitiva: la acción principal debe ser evidente y los detalles permanecer progresivos.',
'Confirmar comportamiento en Safari iOS y escritorio, incluyendo persistencia, teclado, scroll y controles nativos.',
'Tarea generada para stress QA. Puede editarse, moverse, duplicarse, comentarse y eliminarse sin afectar datos reales.'
];
const boardSpecs=[
{id:'product',title:'Bardo · Producto',description:'Diseño y construcción del producto. Dataset principal para probar el Kanban.',count:180,columns:['Backlog','Por hacer','En curso','Hecho']},
{id:'design',title:'Design System',description:'Trabajo visual, componentes y consistencia entre módulos.',count:120,columns:['Ideas','Listo','Diseñando','Validado']},
{id:'launch',title:'Lanzamiento',description:'Preparación, QA y seguimiento de una release simulada.',count:90,columns:['Pendiente','Preparando','QA','Publicado']},
{id:'personal',title:'Personal',description:'Tablero pequeño para probar contextos menos densos.',count:80,columns:['Algún día','Esta semana','Hoy','Listo']}
];
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const clone=o=>JSON.parse(JSON.stringify(o));
const uid=p=>`${p}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,8)}`;
const nowIso=()=>new Date().toISOString();
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function rng(seed){return()=>{seed|=0;seed=seed+0x6D2B79F5|0;let t=Math.imul(seed^seed>>>15,1|seed);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296}}
function dateOffset(days){const d=new Date();d.setHours(12,0,0,0);d.setDate(d.getDate()+days);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function daysFromToday(date){if(!date)return null;const [y,m,d]=date.split('-').map(Number),target=Date.UTC(y,m-1,d),n=new Date(),today=Date.UTC(n.getFullYear(),n.getMonth(),n.getDate());return Math.round((target-today)/86400000)}
function humanDue(date){const d=daysFromToday(date);if(d===null)return'';if(d===0)return'Hoy';if(d===1)return'Mañana';if(d===-1)return'Ayer';if(d<0)return`${Math.abs(d)}d tarde`;if(d<=7)return`En ${d}d`;return date.slice(5).split('-').reverse().join('/')}
function person(id){return people.find(p=>p.id===id)}
function makeSeed(){const r=rng(260823);const boards=boardSpecs.map((spec,bi)=>{const columns=spec.columns.map((title,i)=>({id:`${spec.id}-c${i+1}`,title}));const per=new Map(columns.map(c=>[c.id,0]));const tasks=[];for(let i=0;i<spec.count;i++){const col=columns[Math.floor(r()*columns.length)],order=per.get(col.id);per.set(col.id,order+1);const assignee=r()<.13?'':people[Math.floor(r()*people.length)].id;const priority=priorities[Math.floor(r()*priorities.length)];const dueRoll=Math.floor(r()*55)-18;const due=r()<.18?'':dateOffset(dueRoll);const labelCount=1+Math.floor(r()*3);const labs=[];while(labs.length<labelCount){const l=labelsPool[Math.floor(r()*labelsPool.length)];if(!labs.includes(l))labs.push(l)}const subtasks=[];if(r()<.32){const n=2+Math.floor(r()*4);for(let s=0;s<n;s++)subtasks.push({id:`seed-st-${bi}-${i}-${s}`,text:['Revisar caso','Validar mobile','Registrar evidencia','Confirmar copy','Probar error'][s%5],done:r()<.45})}const comments=[];if(r()<.25){const n=1+Math.floor(r()*3);for(let c=0;c<n;c++)comments.push({id:`seed-cm-${bi}-${i}-${c}`,author:people[Math.floor(r()*people.length)].id,text:['Se ve bien en desktop; falta revisar iPhone.','Encontré un edge case al cambiar de estado.','Validado con datos mock.','Pendiente confirmar el comportamiento del undo.'][c%4],created:new Date(Date.now()-(c+1)*86400000).toISOString()})}tasks.push({id:`${spec.id}-t${i+1}`,title:`${titleStarts[Math.floor(r()*titleStarts.length)]} ${titleEnds[Math.floor(r()*titleEnds.length)]}`,description:descriptions[Math.floor(r()*descriptions.length)],status:col.id,assignee,due,labels:labs,priority,estimate:[0,1,2,3,5,8,13][Math.floor(r()*7)],source:sources[Math.floor(r()*sources.length)],created:new Date(Date.now()-(5+Math.floor(r()*45))*86400000).toISOString(),updated:new Date(Date.now()-Math.floor(r()*10)*86400000).toISOString(),order,subtasks,comments})}return{id:spec.id,title:spec.title,description:spec.description,columns,tasks}});return{version:VERSION,activeBoardId:'product',activeColumnId:'product-c1',filters:[],sort:'manual',boards}}
function sanitizeState(raw){if(!raw||raw.version!==VERSION||!Array.isArray(raw.boards)||!raw.boards.length)throw new Error('invalid');for(const b of raw.boards){if(!b.id||!Array.isArray(b.columns)||b.columns.length<2||!Array.isArray(b.tasks))throw new Error('invalid board');const ids=new Set(b.columns.map(c=>c.id));b.tasks=b.tasks.filter(t=>t&&t.id&&ids.has(t.status)).map(t=>({...t,labels:Array.isArray(t.labels)?t.labels.slice(0,MAX_LABELS):[],subtasks:Array.isArray(t.subtasks)?t.subtasks.slice(0,MAX_SUBTASKS):[],comments:Array.isArray(t.comments)?t.comments.slice(0,MAX_COMMENTS):[],estimate:Number.isFinite(+t.estimate)?Math.max(0,Math.min(100,+t.estimate)):0}))}if(!raw.boards.some(b=>b.id===raw.activeBoardId))raw.activeBoardId=raw.boards[0].id;const b=raw.boards.find(x=>x.id===raw.activeBoardId);if(!b.columns.some(c=>c.id===raw.activeColumnId))raw.activeColumnId=b.columns[0].id;raw.filters=Array.isArray(raw.filters)?raw.filters:[];raw.sort=['manual','priority','due','updated','title'].includes(raw.sort)?raw.sort:'manual';return raw}
let state;try{state=sanitizeState(JSON.parse(localStorage.getItem(STORAGE)||'null'))}catch(_){state=makeSeed()}
let undo=null,toastTimer=null,activeTaskId=null,saveTimer=null,dragTaskId=null,settingsDraft=[],renderLimits=new Map();
function persist(){try{localStorage.setItem(STORAGE,JSON.stringify(state));return true}catch(e){showToast('Storage lleno: los cambios siguen en memoria',false);console.warn(e);return false}}
function currentBoard(){return state.boards.find(b=>b.id===state.activeBoardId)||state.boards[0]}
function taskById(id){return currentBoard().tasks.find(t=>t.id===id)}
function normalizeOrders(board=currentBoard()){for(const c of board.columns){board.tasks.filter(t=>t.status===c.id).sort((a,b)=>a.order-b.order).forEach((t,i)=>t.order=i)}}
function snapshot(label){undo={label,state:clone(state)}}
function commit(label,fn,msg=label){snapshot(label);fn();normalizeOrders();persist();render();showToast(msg,true)}
function undoLast(){if(!undo)return;state=sanitizeState(clone(undo.state));undo=null;persist();render();showToast('Cambio deshecho',false)}
function showToast(text,canUndo=false){$('#toast-text').textContent=text;$('#toast-undo').hidden=!canUndo;$('#toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').hidden=true,4500)}
function visibleTasks(board,colId){let list=board.tasks.filter(t=>t.status===colId&&matches(t));switch(state.sort){case'priority':list.sort((a,b)=>priorityRank[a.priority]-priorityRank[b.priority]||a.order-b.order);break;case'due':list.sort((a,b)=>(a.due||'9999').localeCompare(b.due||'9999'));break;case'updated':list.sort((a,b)=>b.updated.localeCompare(a.updated));break;case'title':list.sort((a,b)=>a.title.localeCompare(b.title,'es'));break;default:list.sort((a,b)=>a.order-b.order)}return list}
function matches(t){const q=$('#search').value.trim().toLowerCase();if(q){const hay=[t.title,t.description,t.assignee,t.source,...t.labels,...t.comments.map(c=>c.text),...t.subtasks.map(s=>s.text)].join(' ').toLowerCase();if(!hay.includes(q))return false}const d=daysFromToday(t.due);for(const f of state.filters){if(f==='mine'&&t.assignee!==ME)return false;if(f==='urgent'&&t.priority!=='urgent')return false;if(f==='overdue'&&!(d!==null&&d<0))return false;if(f==='soon'&&!(d!==null&&d>=0&&d<=7))return false;if(f==='unassigned'&&t.assignee)return false}return true}
function countVisible(board){return board.tasks.filter(matches).length}
function render(){const b=currentBoard();if(!b.columns.some(c=>c.id===state.activeColumnId))state.activeColumnId=b.columns[0].id;$('#board-title').textContent=b.title;$('#board-description').textContent=b.description;const doneCol=b.columns[b.columns.length-1].id,done=b.tasks.filter(t=>t.status===doneCol).length;$('#board-stats').innerHTML=`<span>${b.tasks.length.toLocaleString('es-CL')} tareas</span><span>${countVisible(b).toLocaleString('es-CL')} visibles</span><span>${done.toLocaleString('es-CL')} en ${esc(b.columns[b.columns.length-1].title)}</span><span>${b.columns.length} columnas</span>`;$('#sort').value=state.sort;renderFilters();renderTabs();renderBoard();renderBoardPicker();renderQa();document.documentElement.style.setProperty('--cols',Math.min(6,b.columns.length))}
function renderFilters(){$$('.chip[data-filter]').forEach(btn=>{const f=btn.dataset.filter;btn.classList.toggle('active',f==='all'?state.filters.length===0:state.filters.includes(f))})}
function renderTabs(){const b=currentBoard();$('#mobile-tabs').innerHTML=b.columns.map(c=>`<button type="button" class="tab ${c.id===state.activeColumnId?'active':''}" data-col-tab="${esc(c.id)}">${esc(c.title)} <span>${visibleTasks(b,c.id).length}</span></button>`).join('')}
function renderBoard(){const b=currentBoard();$('#board').innerHTML=b.columns.map(c=>renderColumn(b,c)).join('')}
function renderColumn(b,c){const all=visibleTasks(b,c.id),key=`${b.id}:${c.id}`,limit=renderLimits.get(key)||100,shown=all.slice(0,limit);return`<section class="column ${c.id===state.activeColumnId?'active':''}" data-column="${esc(c.id)}"><header class="column-head"><h2>${esc(c.title)} <small>${all.length}</small></h2><button class="column-add" type="button" data-add-column-task="${esc(c.id)}" aria-label="Crear tarea en ${esc(c.title)}">＋</button></header><div class="task-list" data-list="${esc(c.id)}">${shown.length?shown.map(renderCard).join(''):`<div class="empty">No hay tareas con estos filtros.</div>`}${all.length>limit?`<button type="button" class="btn ghost more-btn" data-more="${esc(c.id)}">Mostrar ${Math.min(100,all.length-limit)} más · quedan ${all.length-limit}</button>`:''}</div></section>`}
function renderCard(t){const p=person(t.assignee),d=daysFromToday(t.due),dueClass=d!==null&&d<0?'overdue':d!==null&&d<=7?'soon':'';const progress=t.subtasks.length?`${t.subtasks.filter(s=>s.done).length}/${t.subtasks.length}`:'';return`<article class="task-card" draggable="true" tabindex="0" role="button" data-task="${esc(t.id)}" data-priority="${t.priority}" aria-label="Abrir ${esc(t.title)}"><span class="task-title">${esc(t.title)}</span><span class="task-desc">${esc(t.description)}</span><div class="task-meta"><div class="meta-left">${t.labels.slice(0,2).map(l=>`<span class="label">${esc(l)}</span>`).join('')}${t.due?`<span class="due ${dueClass}">${humanDue(t.due)}</span>`:''}${progress?`<span class="due">☑ ${progress}</span>`:''}</div><span class="avatar" title="${p?esc(p.name):'Sin responsable'}">${p?p.initials:'—'}</span></div></article>`}
function renderBoardPicker(){const b=currentBoard();$('#board-list').innerHTML=state.boards.map(x=>`<div class="board-row"><button type="button" class="${x.id===b.id?'active':''}" data-board="${esc(x.id)}"><strong>${esc(x.title)}</strong><small>${x.tasks.length.toLocaleString('es-CL')} tareas · ${x.columns.length} columnas</small></button></div>`).join('')}
function renderQa(){const b=currentBoard(),subs=b.tasks.reduce((n,t)=>n+t.subtasks.length,0),comments=b.tasks.reduce((n,t)=>n+t.comments.length,0);$('#qa-kpis').innerHTML=`<div class="qa-kpi"><strong>${b.tasks.length.toLocaleString('es-CL')}</strong><span>tareas</span></div><div class="qa-kpi"><strong>${subs.toLocaleString('es-CL')}</strong><span>subtareas</span></div><div class="qa-kpi"><strong>${comments.toLocaleString('es-CL')}</strong><span>comentarios</span></div>`}
function openDialog(id){const d=$(`#${id}`);if(!d.open)d.showModal()}
function closeDialog(d){if(typeof d==='string')d=$(`#${d}`);if(d?.open)d.close()}
function fillPeople(){const opts='<option value="">Sin responsable</option>'+people.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('');$('#task-assignee').innerHTML=opts}
function fillStatus(select,b=currentBoard()){select.innerHTML=b.columns.map(c=>`<option value="${c.id}">${esc(c.title)}</option>`).join('')}
function openQuick(status=state.activeColumnId){fillStatus($('#quick-status'));$('#quick-status').value=currentBoard().columns.some(c=>c.id===status)?status:currentBoard().columns[0].id;$('#quick-title').value='';$('#quick-priority').value='normal';openDialog('quick-dialog');setTimeout(()=>$('#quick-title').focus(),30)}
function createTask(title,status,priority='normal'){const b=currentBoard(),order=b.tasks.filter(t=>t.status===status).length,t={id:uid('task'),title:title.trim().slice(0,180),description:'',status,assignee:'',due:'',labels:[],priority,estimate:0,source:'Manual',created:nowIso(),updated:nowIso(),order,subtasks:[],comments:[]};commit('crear tarea',()=>{b.tasks.push(t);state.activeColumnId=status},'Tarea creada');return t}
function openTask(id){flushTaskSave();const t=taskById(id);if(!t)return;activeTaskId=id;fillStatus($('#task-status'));fillPeople();$('#task-id').textContent=t.id;$('#task-title').value=t.title;$('#task-description').value=t.description;$('#task-status').value=t.status;$('#task-assignee').value=t.assignee;$('#task-priority').value=t.priority;$('#task-due').value=t.due||'';$('#task-estimate').value=t.estimate||0;$('#task-source').value=t.source||'Manual';$('#task-labels').value=t.labels.join(', ');$('#save-state').textContent='Guardado';renderTaskExtras();openDialog('task-dialog')}
function renderTaskExtras(){const t=taskById(activeTaskId);if(!t)return;const done=t.subtasks.filter(s=>s.done).length;$('#subtask-progress').textContent=t.subtasks.length?`${done}/${t.subtasks.length}`:'0';$('#subtasks').innerHTML=t.subtasks.length?t.subtasks.map(s=>`<div class="subtask ${s.done?'done':''}" data-subtask="${s.id}"><label><input type="checkbox" ${s.done?'checked':''}><span>${esc(s.text)}</span></label><button type="button" data-remove-subtask="${s.id}" aria-label="Eliminar subtarea">×</button></div>`).join(''):'<div class="empty">Sin subtareas.</div>';$('#comment-count').textContent=t.comments.length;$('#comments').innerHTML=t.comments.length?t.comments.slice().reverse().map(c=>{const p=person(c.author);return`<div class="comment" data-comment="${c.id}"><div class="comment-head"><span>${esc(p?.name||'Usuario')}</span><button type="button" data-remove-comment="${c.id}">Eliminar</button></div><p>${esc(c.text)}</p></div>`}).join(''):'<div class="empty">Sin comentarios.</div>'}
function scheduleTaskSave(){const t=taskById(activeTaskId);if(!t)return;$('#save-state').textContent='Guardando…';clearTimeout(saveTimer);saveTimer=setTimeout(flushTaskSave,260)}
function flushTaskSave(){clearTimeout(saveTimer);saveTimer=null;const t=taskById(activeTaskId);if(!t||!$('#task-dialog').open)return;const oldStatus=t.status,newStatus=$('#task-status').value;t.title=($('#task-title').value.trim()||'Sin título').slice(0,180);t.description=$('#task-description').value.slice(0,3000);t.status=newStatus;t.assignee=$('#task-assignee').value;t.priority=$('#task-priority').value;t.due=$('#task-due').value;t.estimate=Math.max(0,Math.min(100,Number($('#task-estimate').value)||0));t.source=$('#task-source').value;t.labels=[...new Set($('#task-labels').value.split(',').map(s=>s.trim()).filter(Boolean))].slice(0,MAX_LABELS);t.updated=nowIso();if(oldStatus!==newStatus)t.order=currentBoard().tasks.filter(x=>x.status===newStatus&&x.id!==t.id).length;normalizeOrders();persist();$('#save-state').textContent='Guardado';render()}
function renderSettings(){const b=currentBoard();settingsDraft=clone(b.columns);$('#settings-title').value=b.title;$('#settings-description').value=b.description;renderColumnSettings();renderQa();$('#self-test-output').hidden=true}
function renderColumnSettings(){const b=currentBoard();$('#columns-settings').innerHTML=settingsDraft.map((c,i)=>{const count=b.tasks.filter(t=>t.status===c.id).length;return`<div class="column-setting" data-setting-col="${c.id}"><span title="Orden">⋮⋮</span><input maxlength="28" value="${esc(c.title)}" aria-label="Nombre de columna"><button class="mini" type="button" data-col-up="${c.id}" ${i===0?'disabled':''}>↑</button><button class="mini" type="button" data-col-down="${c.id}" ${i===settingsDraft.length-1?'disabled':''}>↓</button><button class="mini" type="button" data-col-delete="${c.id}" title="${count?`${count} tareas`: 'Eliminar'}">×</button></div>`}).join('')}
function addStress(count){const b=currentBoard(),before=performance.now(),counts=new Map(b.columns.map(c=>[c.id,b.tasks.filter(t=>t.status===c.id).length]));snapshot(`añadir ${count}`);for(let i=0;i<count;i++){const c=b.columns[i%b.columns.length],order=counts.get(c.id);counts.set(c.id,order+1);b.tasks.push({id:uid('stress'),title:`Stress ${String(i+1).padStart(4,'0')} · ${titleEnds[i%titleEnds.length]}`,description:descriptions[4],status:c.id,assignee:i%7===0?'':people[i%people.length].id,due:i%6===0?dateOffset((i%31)-10):'',labels:[labelsPool[i%labelsPool.length],labelsPool[(i+4)%labelsPool.length]],priority:priorities[i%priorities.length],estimate:[1,2,3,5,8][i%5],source:sources[i%sources.length],created:nowIso(),updated:nowIso(),order,subtasks:i%5===0?[{id:uid('st'),text:'Verificar comportamiento',done:i%2===0},{id:uid('st'),text:'Registrar resultado',done:false}]:[],comments:i%8===0?[{id:uid('cm'),author:ME,text:'Comentario mock de estrés.',created:nowIso()}]:[]})}persist();render();showToast(`${count.toLocaleString('es-CL')} tareas añadidas · ${(performance.now()-before).toFixed(0)} ms`,true)}
function selfTest(){const fails=[],lines=[],check=(name,ok)=>{lines.push(`${ok?'PASS':'FAIL'}  ${name}`);if(!ok)fails.push(name)};const start=performance.now();check('Hay tableros',state.boards.length>0);check('IDs de tablero únicos',new Set(state.boards.map(b=>b.id)).size===state.boards.length);check('2–8 columnas por tablero',state.boards.every(b=>b.columns.length>=2&&b.columns.length<=MAX_COLUMNS));check('Columnas únicas',state.boards.every(b=>new Set(b.columns.map(c=>c.id)).size===b.columns.length));check('Tareas apuntan a columnas válidas',state.boards.every(b=>{const ids=new Set(b.columns.map(c=>c.id));return b.tasks.every(t=>ids.has(t.status))}));check('IDs de tarea únicos por tablero',state.boards.every(b=>new Set(b.tasks.map(t=>t.id)).size===b.tasks.length));check('Prioridades válidas',state.boards.every(b=>b.tasks.every(t=>priorities.includes(t.priority))));check('Etiquetas acotadas',state.boards.every(b=>b.tasks.every(t=>t.labels.length<=MAX_LABELS)));check('Subtareas acotadas',state.boards.every(b=>b.tasks.every(t=>t.subtasks.length<=MAX_SUBTASKS)));check('Comentarios acotados',state.boards.every(b=>b.tasks.every(t=>t.comments.length<=MAX_COMMENTS)));check('Orden manual consistente',state.boards.every(b=>b.columns.every(c=>b.tasks.filter(t=>t.status===c.id).sort((a,z)=>a.order-z.order).every((t,i)=>t.order===i))));check('Estado serializable',(()=>{try{JSON.stringify(state);return true}catch(_){return false}})());const out=$('#self-test-output');out.hidden=false;out.textContent=`${lines.join('\n')}\n\n${fails.length?`${fails.length} fallo(s)`:'Todo consistente'} · ${(performance.now()-start).toFixed(1)} ms · ${state.boards.reduce((n,b)=>n+b.tasks.length,0).toLocaleString('es-CL')} tareas`;showToast(fails.length?`Autoprueba: ${fails.length} fallos`:'Autoprueba superada',false)}
function moveTask(id,toStatus){const b=currentBoard(),t=b.tasks.find(x=>x.id===id);if(!t||t.status===toStatus)return;commit('mover tarea',()=>{t.status=toStatus;t.order=b.tasks.filter(x=>x.status===toStatus&&x.id!==id).length;t.updated=nowIso();state.activeColumnId=toStatus},'Tarea movida')}
function createBoard(){const title=prompt('Nombre del nuevo tablero','Nuevo tablero');if(!title?.trim())return;const id=uid('board'),cols=['Backlog','Por hacer','En curso','Hecho'].map((title,i)=>({id:`${id}-c${i+1}`,title}));commit('crear tablero',()=>{state.boards.push({id,title:title.trim().slice(0,48),description:'Tablero mock para validar un flujo aislado.',columns:cols,tasks:[]});state.activeBoardId=id;state.activeColumnId=cols[0].id},'Tablero creado');closeDialog('board-picker-dialog')}
function duplicateBoard(){const b=currentBoard(),copy=clone(b),id=uid('board'),colMap=new Map();copy.id=id;copy.title=`${b.title} · copia`.slice(0,48);copy.columns=copy.columns.map((c,i)=>{const nid=`${id}-c${i+1}`;colMap.set(c.id,nid);return{...c,id:nid}});copy.tasks=copy.tasks.map((t,i)=>({...t,id:`${id}-t${i+1}-${Math.random().toString(36).slice(2,5)}`,status:colMap.get(t.status),subtasks:t.subtasks.map(s=>({...s,id:uid('st')})),comments:t.comments.map(c=>({...c,id:uid('cm')}))}));commit('duplicar tablero',()=>{state.boards.push(copy);state.activeBoardId=id;state.activeColumnId=copy.columns[0].id},'Tablero duplicado');closeDialog('settings-dialog')}
function deleteBoard(){if(state.boards.length<=1){showToast('Debe existir al menos un tablero',false);return}const b=currentBoard();if(!confirm(`Eliminar “${b.title}” y sus ${b.tasks.length} tareas mock?`))return;commit('eliminar tablero',()=>{state.boards=state.boards.filter(x=>x.id!==b.id);state.activeBoardId=state.boards[0].id;state.activeColumnId=state.boards[0].columns[0].id},'Tablero eliminado');closeDialog('settings-dialog')}
function clearBoard(){const b=currentBoard();if(!confirm(`Vaciar las ${b.tasks.length} tareas de “${b.title}”?`))return;commit('vaciar tablero',()=>{b.tasks=[]},'Tablero vacío');closeDialog('settings-dialog')}
function resetAll(){if(!confirm('Restablecer los 470 datos mock iniciales y perder cambios locales?'))return;state=makeSeed();undo=null;activeTaskId=null;renderLimits.clear();persist();closeDialog('settings-dialog');render();showToast('Mocks restablecidos',false)}

$('#search').addEventListener('input',render);
$('#sort').addEventListener('change',e=>{state.sort=e.target.value;persist();render()});
$('.filters').addEventListener('click',e=>{const btn=e.target.closest('[data-filter]');if(!btn)return;const f=btn.dataset.filter;if(f==='all')state.filters=[];else state.filters=state.filters.includes(f)?state.filters.filter(x=>x!==f):[...state.filters,f];persist();render()});
$('#mobile-tabs').addEventListener('click',e=>{const btn=e.target.closest('[data-col-tab]');if(!btn)return;state.activeColumnId=btn.dataset.colTab;persist();render()});
$('#board').addEventListener('click',e=>{const more=e.target.closest('[data-more]');if(more){const key=`${currentBoard().id}:${more.dataset.more}`;renderLimits.set(key,(renderLimits.get(key)||100)+100);render();return}const add=e.target.closest('[data-add-column-task]');if(add){openQuick(add.dataset.addColumnTask);return}const card=e.target.closest('[data-task]');if(card)openTask(card.dataset.task)});
$('#board').addEventListener('keydown',e=>{const card=e.target.closest('[data-task]');if(card&&(e.key==='Enter'||e.key===' ')){e.preventDefault();openTask(card.dataset.task)}});
$('#board').addEventListener('dragstart',e=>{const card=e.target.closest('[data-task]');if(!card)return;dragTaskId=card.dataset.task;card.classList.add('dragging');e.dataTransfer.effectAllowed='move';e.dataTransfer.setData('text/plain',dragTaskId)});
$('#board').addEventListener('dragend',e=>{e.target.closest('[data-task]')?.classList.remove('dragging');$$('.task-list.dragover').forEach(x=>x.classList.remove('dragover'));dragTaskId=null});
$('#board').addEventListener('dragover',e=>{const list=e.target.closest('[data-list]');if(!list)return;e.preventDefault();list.classList.add('dragover');e.dataTransfer.dropEffect='move'});
$('#board').addEventListener('dragleave',e=>{const list=e.target.closest('[data-list]');if(list&&!list.contains(e.relatedTarget))list.classList.remove('dragover')});
$('#board').addEventListener('drop',e=>{const list=e.target.closest('[data-list]');if(!list)return;e.preventDefault();list.classList.remove('dragover');const id=dragTaskId||e.dataTransfer.getData('text/plain');moveTask(id,list.dataset.list)});
['new-task-top','new-task-hero','new-task-fab'].forEach(id=>$(`#${id}`).addEventListener('click',()=>openQuick()));
$('#board-picker-btn').addEventListener('click',()=>openDialog('board-picker-dialog'));
$('#open-settings').addEventListener('click',()=>{renderSettings();openDialog('settings-dialog')});
$('#board-list').addEventListener('click',e=>{const btn=e.target.closest('[data-board]');if(!btn)return;state.activeBoardId=btn.dataset.board;state.activeColumnId=currentBoard().columns[0].id;renderLimits.clear();persist();render();closeDialog('board-picker-dialog')});
$('#create-board').addEventListener('click',createBoard);
$('#quick-form').addEventListener('submit',e=>{e.preventDefault();const title=$('#quick-title').value.trim();if(!title){$('#quick-title').focus();return}createTask(title,$('#quick-status').value,$('#quick-priority').value);closeDialog('quick-dialog')});
$$('.close').forEach(btn=>btn.addEventListener('click',()=>{if(btn.closest('#task-dialog'))flushTaskSave();closeDialog(btn.closest('dialog'))}));
$$('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target===d){if(d.id==='task-dialog')flushTaskSave();d.close()}}));
$('#toast-undo').addEventListener('click',undoLast);

['task-title','task-description','task-status','task-assignee','task-priority','task-due','task-estimate','task-source','task-labels'].forEach(id=>$(`#${id}`).addEventListener(['task-status','task-assignee','task-priority','task-due','task-source'].includes(id)?'change':'input',scheduleTaskSave));
$('#add-subtask').addEventListener('click',()=>{const t=taskById(activeTaskId),input=$('#subtask-input'),text=input.value.trim();if(!t||!text)return;if(t.subtasks.length>=MAX_SUBTASKS){showToast(`Máximo ${MAX_SUBTASKS} subtareas`,false);return}t.subtasks.push({id:uid('st'),text:text.slice(0,120),done:false});t.updated=nowIso();input.value='';persist();renderTaskExtras();render()});
$('#subtask-input').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();$('#add-subtask').click()}});
$('#subtasks').addEventListener('change',e=>{const row=e.target.closest('[data-subtask]'),t=taskById(activeTaskId);if(!row||!t)return;const s=t.subtasks.find(x=>x.id===row.dataset.subtask);if(s){s.done=e.target.checked;t.updated=nowIso();persist();renderTaskExtras();render()}});
$('#subtasks').addEventListener('click',e=>{const btn=e.target.closest('[data-remove-subtask]'),t=taskById(activeTaskId);if(!btn||!t)return;t.subtasks=t.subtasks.filter(s=>s.id!==btn.dataset.removeSubtask);t.updated=nowIso();persist();renderTaskExtras();render()});
$('#add-comment').addEventListener('click',()=>{const t=taskById(activeTaskId),input=$('#comment-input'),text=input.value.trim();if(!t||!text)return;if(t.comments.length>=MAX_COMMENTS){showToast(`Máximo ${MAX_COMMENTS} comentarios`,false);return}t.comments.push({id:uid('cm'),author:ME,text:text.slice(0,500),created:nowIso()});t.updated=nowIso();input.value='';persist();renderTaskExtras();render()});
$('#comments').addEventListener('click',e=>{const btn=e.target.closest('[data-remove-comment]'),t=taskById(activeTaskId);if(!btn||!t)return;t.comments=t.comments.filter(c=>c.id!==btn.dataset.removeComment);t.updated=nowIso();persist();renderTaskExtras();render()});
$('#duplicate-task').addEventListener('click',()=>{flushTaskSave();const b=currentBoard(),t=taskById(activeTaskId);if(!t)return;const copy=clone(t);copy.id=uid('task');copy.title=`${t.title} · copia`.slice(0,180);copy.created=copy.updated=nowIso();copy.order=b.tasks.filter(x=>x.status===t.status).length;copy.subtasks=copy.subtasks.map(s=>({...s,id:uid('st')}));copy.comments=copy.comments.map(c=>({...c,id:uid('cm')}));commit('duplicar tarea',()=>b.tasks.push(copy),'Tarea duplicada');activeTaskId=copy.id;openTask(copy.id)});
$('#delete-task').addEventListener('click',()=>{flushTaskSave();const b=currentBoard(),t=taskById(activeTaskId);if(!t||!confirm(`Eliminar “${t.title}”?`))return;commit('eliminar tarea',()=>{b.tasks=b.tasks.filter(x=>x.id!==t.id)},'Tarea eliminada');activeTaskId=null;closeDialog('task-dialog')});

$('#add-column').addEventListener('click',()=>{if(settingsDraft.length>=MAX_COLUMNS){showToast(`Máximo ${MAX_COLUMNS} columnas`,false);return}settingsDraft.push({id:uid('col'),title:`Columna ${settingsDraft.length+1}`});renderColumnSettings()});
$('#columns-settings').addEventListener('click',e=>{const up=e.target.closest('[data-col-up]'),down=e.target.closest('[data-col-down]'),del=e.target.closest('[data-col-delete]');if(up||down){const id=(up||down).dataset[up?'colUp':'colDown'],i=settingsDraft.findIndex(c=>c.id===id),j=up?i-1:i+1;if(j>=0&&j<settingsDraft.length)[settingsDraft[i],settingsDraft[j]]=[settingsDraft[j],settingsDraft[i]];renderColumnSettings();return}if(del){const id=del.dataset.colDelete,count=currentBoard().tasks.filter(t=>t.status===id).length;if(count){showToast(`No puedes borrar: contiene ${count} tareas`,false);return}if(settingsDraft.length<=2){showToast('Mínimo 2 columnas',false);return}settingsDraft=settingsDraft.filter(c=>c.id!==id);renderColumnSettings()}});
$('#save-settings').addEventListener('click',()=>{const b=currentBoard(),inputs=$$('#columns-settings input');const title=$('#settings-title').value.trim();if(!title){$('#settings-title').focus();return}const next=settingsDraft.map((c,i)=>({...c,title:(inputs[i]?.value.trim()||'').slice(0,28)}));if(next.some(c=>!c.title)){showToast('Todas las columnas necesitan nombre',false);return}snapshot('configurar tablero');b.title=title.slice(0,48);b.description=$('#settings-description').value.trim().slice(0,180);b.columns=next;if(!b.columns.some(c=>c.id===state.activeColumnId))state.activeColumnId=b.columns[0].id;normalizeOrders();persist();render();closeDialog('settings-dialog');showToast('Tablero actualizado',true)});
$('#duplicate-board').addEventListener('click',duplicateBoard);$('#delete-board').addEventListener('click',deleteBoard);$('#stress-250').addEventListener('click',()=>addStress(250));$('#stress-1000').addEventListener('click',()=>addStress(1000));$('#self-test').addEventListener('click',selfTest);$('#clear-board').addEventListener('click',clearBoard);$('#reset-all').addEventListener('click',resetAll);

document.addEventListener('keydown',e=>{const editable=e.target.matches('input,textarea,select,[contenteditable="true"]');if(e.key==='Escape'){const d=$('dialog[open]');if(d){if(d.id==='task-dialog')flushTaskSave();d.close()}return}if(editable)return;if(e.key==='n'||e.key==='N'){e.preventDefault();openQuick()}if(e.key==='/'){e.preventDefault();$('#search').focus()}});
window.addEventListener('beforeunload',flushTaskSave);
window.__BARDO_QA__={getState:()=>clone(state),reset:resetAll,selfTest,addStress,openTask,visibleCount:()=>countVisible(currentBoard())};
fillPeople();render();
})();
